# Generated by Django 3.0.8 on 2020-09-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('tipo_id', models.CharField(choices=[('1', 'Cédula de Identidad'), ('2', 'RTN'), ('3', 'Otro')], default='1', max_length=1, verbose_name='Tipo de Identificación')),
                ('identidad', models.CharField(blank=True, max_length=30)),
                ('fch_nacimiento', models.CharField(blank=True, max_length=30, verbose_name='fecha de nacimiento')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Códigos',
                'ordering': ['id_codigo'],
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['id_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=120, verbose_name='Nombre de la empresa')),
                ('descripcion', models.CharField(blank=True, max_length=450, verbose_name='Descripción')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('nombre_contacto', models.CharField(blank=True, max_length=80, verbose_name='Nombre del contacto')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['id_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('fch_recordatorio', models.DateField()),
                ('hora_recordatorio', models.TimeField()),
                ('descripción', models.TextField()),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Recordatorios Cliente',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Departamentos')),
            ],
            options={
                'verbose_name_plural': 'Puestos',
                'ordering': ['id_puesto'],
            },
        ),
        migrations.CreateModel(
            name='Promesas',
            fields=[
                ('id_promesa', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('estatus_promesa', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Cumplida'), ('3', 'Incumplida')], default='1', max_length=1, verbose_name='Estatus de la Promesa')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Promesas',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('numero_producto', models.CharField(max_length=50)),
                ('dias_mora', models.IntegerField()),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=19)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Productos Cliente',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
                ('id_promesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cobros.Promesas')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Codigos')),
            ],
            options={
                'verbose_name_plural': 'Motivos',
                'ordering': ['id_motivo'],
            },
        ),
        migrations.CreateModel(
            name='LogCobros',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tabla', models.CharField(max_length=35)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('tipo_accion', models.CharField(choices=[('Insertar', 'Insertar'), ('Modificar', 'Modificar'), ('Seleccionar', 'Seleccionar'), ('Borrar', 'Borrar')], max_length=35, verbose_name='Tipo de Acción')),
                ('Dato_anterior', models.CharField(blank=True, max_length=400)),
                ('Dato_despues', models.CharField(blank=True, max_length=400)),
                ('campo_afectado', models.CharField(blank=True, max_length=35)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Bitácora App Cobros',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('id_gestion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fch_gestion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Codigos')),
                ('id_motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Motivos')),
            ],
            options={
                'verbose_name_plural': 'Gestiones',
                'ordering': ['-fch_gestion'],
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contacto', models.CharField(choices=[('Teléfono Trabajo', 'Teléfono Trabajo'), ('Teléfono Casa', 'Teléfono Casa'), ('Celular', 'Celular'), ('Dirección Casa', 'Dirección Casa'), ('Dirección Trabajo', 'Dirección Trabajo'), ('Correo', 'Correo')], default='Teléfono', max_length=35)),
                ('descripcion', models.TextField()),
                ('comentario', models.CharField(max_length=200)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Contactos Cliente',
                'ordering': ['tipo_contacto'],
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Empresas', verbose_name='Empresa'),
        ),
    ]
