# Generated by Django 3.0.8 on 2020-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='codigos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='contactos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='empresas',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='gestiones',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='motivos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='pagos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='productos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='promesas',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='puestos',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='recordatorios',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='borrado',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Fch_ingreso_labores',
            field=models.DateField(),
        ),
    ]
