# Generated by Django 3.0.8 on 2020-09-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_auto_20200909_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/%Y/%m/%d'),
        ),
    ]
