# Generated by Django 3.0.8 on 2020-09-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobros', '0002_auto_20200922_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestiones',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='gestiones',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
