# Generated by Django 3.0.8 on 2020-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_auto_20200922_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motivos',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
