# Generated by Django 3.0.8 on 2020-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_departamentos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='imagen',
        ),
    ]
