# Generated by Django 3.0.8 on 2020-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_auto_20200923_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='id_promesa',
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Unión Libre')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fch_nacimiento',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fecha de nacimiento'),
        ),
    ]
