# Generated by Django 3.0.8 on 2020-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_remove_departamentos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
