# Generated by Django 3.0.8 on 2020-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0005_auto_20200915_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codigos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestiones',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motivos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promesas',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordatorios',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
