# Generated by Django 3.0.8 on 2020-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0005_auto_20200924_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Unión Libre', 'Unión Libre')], default='Soltero', max_length=12),
        ),
    ]
