# Generated by Django 3.0.8 on 2020-09-24 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobros', '0006_auto_20200924_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
