# Generated by Django 3.0.8 on 2020-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0007_auto_20200916_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='productos',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dias_mora',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='intereses',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='productos',
            name='saldo_total',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='promesas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
