# Generated by Django 3.0.8 on 2020-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0007_auto_20200924_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promesas',
            name='estatus_promesa',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cumplida', 'Cumplida'), ('Incumplida', 'Incumplida')], default='Pendiente', max_length=11, verbose_name='Estatus de la Promesa'),
        ),
    ]
