# Generated by Django 3.0.8 on 2020-09-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0008_auto_20200916_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigos',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
