# Generated by Django 3.0.8 on 2020-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0008_auto_20200924_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='promesas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
