# Generated by Django 3.0.8 on 2020-09-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobros', '0009_auto_20200924_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('fch_visita_realizada', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=1500)),
                ('respuesta_visita', models.CharField(blank=True, max_length=1500)),
                ('estatus_visita', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Localizado sin Promesa', 'Localizado sin Promesa'), ('Localizado con Promesa', 'Localizado con Promesa'), ('Dirección Incorrecta', 'Dirección Incorrecta')], default='Pendiente', max_length=25, verbose_name='Estatus de la Visita')),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Clientes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Visitas',
                'ordering': ['id_cliente'],
            },
        ),
    ]
