# Generated by Django 3.0.8 on 2020-09-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0010_auto_20200917_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestiones',
            name='fch_creacion',
        ),
    ]
