# Generated by Django 3.0.8 on 2020-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0011_auto_20200924_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatorios',
            name='hora_recordatorio',
        ),
        migrations.AlterField(
            model_name='recordatorios',
            name='fch_recordatorio',
            field=models.DateTimeField(),
        ),
    ]
