# Generated by Django 3.0.8 on 2020-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0012_auto_20200924_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorios',
            name='fch_recordatorio',
            field=models.DateField(),
        ),
    ]
