# Generated by Django 3.0.8 on 2020-09-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0012_auto_20200918_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestiones',
            options={'ordering': ['-id_gestion'], 'verbose_name_plural': 'Gestiones'},
        ),
    ]
