# Generated by Django 3.0.8 on 2020-09-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0014_recordatorios_hora_recordatorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordatorios',
            old_name='descripcion',
            new_name='descripcion_alerta',
        ),
    ]
