# Generated by Django 3.0.8 on 2020-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0015_auto_20200925_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='promesas',
            name='motivo_descrip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
