# Generated by Django 3.0.8 on 2020-09-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0016_promesas_motivo_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='motivo_descrip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
