# Generated by Django 3.0.8 on 2020-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0017_visitas_motivo_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fch_visita_realizada',
            field=models.DateField(null=True),
        ),
    ]
