# Generated by Django 3.0.8 on 2020-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0018_auto_20200925_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fch_visita_realizada',
            field=models.DateField(blank=True),
        ),
    ]
