# Generated by Django 3.0.8 on 2020-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0020_auto_20200925_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='nombre_empresa',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre de la empresa'),
        ),
    ]
