# Generated by Django 3.0.8 on 2020-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0021_auto_20200930_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='motivos',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
