# Generated by Django 3.0.8 on 2020-09-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobros', '0022_auto_20200930_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcobros',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='logcobros',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
