# Generated by Django 3.0.8 on 2020-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0024_recordatorios_estatus_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordatorios',
            name='descripcion_alerta',
            field=models.CharField(max_length=50),
        ),
    ]
