# Generated by Django 3.0.8 on 2020-09-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('ip_ultimo_acceso', models.CharField(blank=True, max_length=50)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('cambiar_contrasenia', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='1', max_length=1)),
                ('bloqueado', models.CharField(choices=[('1', 'Bloqueado'), ('0', 'Desbloqueado')], default='0', max_length=1)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Departamentos', verbose_name='Departamento')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobros.Puestos', verbose_name='Puesto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
