# Generated by Django 3.0.8 on 2020-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_departamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_puesto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puesto'),
        ),
    ]
