# Generated by Django 3.0.8 on 2020-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201002_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fch_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
