# Generated by Django 3.0.8 on 2020-10-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_pantallas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='pantalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Pantallas', verbose_name='Pantalla'),
        ),
    ]
