# Generated by Django 3.0.8 on 2020-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fch_modificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
