# Generated by Django 3.0.8 on 2020-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20201014_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primer_ingreso',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
