# Generated by Django 3.0.8 on 2020-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_primer_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fch_cambio_password',
            field=models.DateTimeField(null=True),
        ),
    ]
